aaproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tasks.urls"))
]

tasks/urls.py
from django.urls import path
from .views import TaskListView, TaskDetailView, CreateTaskView, UpdateTaskView, DeleteTaskView

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("edit/<int:pk>/", UpdateTaskView.as_view(), name="task-update"),
    path("add/", CreateTaskView.as_view(), name='task-create'),
    path("delete/<int:pk>", DeleteTaskView.as_view(), name="task-delete"),
]

tasks/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    review = models.DateField(null=True, blank=True)

    
    def __str__(self):
        return self.title
    
    # def review_time()

tasks/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Task
from datetime import timedelta
from django.utils import timezone


class TaskListView(ListView):
    model = Task
    context_object_name = "tasks"

    def get_queryset(self):

        incomplete_tasks = Task.objects.filter(completed=False)
        review_tasks = Task.objects.filter(review__lte=timezone.localtime().date())


        for task in review_tasks:
            task.completed = False  
            task.review_time = None  
            task.save()  

        # return queryset | review_tasks
            
        queryset = incomplete_tasks.union(review_tasks)
        return queryset


class TaskDetailView(DetailView):
    model = Task


class UpdateTaskView(UpdateView):
    model = Task
    template_name = "tasks/task_update.html"
    fields = ["title", "description", "completed"]
    success_url = reverse_lazy("task-list")
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.completed:
            review_time = form.data.get('review_time')

            if review_time:
                print(1)
                self.object.review = timezone.now() + timedelta(days=int(review_time))

        self.object.save()
        return super().form_valid(form)
    

class CreateTaskView(CreateView):
    model = Task
    fields = ["title", "description"]
    success_url = reverse_lazy("task-list")


class DeleteTaskView(DeleteView):
    model = Task
    success_url = reverse_lazy('task-list')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://unpkg.com/htmx.org@1.9.9" integrity="sha384-QFjmbokDn2DjBjq+fM+8LUIVrAgqcNW2s0PjAxHETgRn9l4fvX31ZxDxvwQnyMOX" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    

    
    <title>Tasks</title>
</head>
<body >


    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url "task-list" %}">Tasks</a>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
    </nav>

    {% block content %}
    
    {% endblock %}
</body>
</html>

templates/tasks/task_delete.html
{% comment %} <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

        <div class="modal-header">
            <h5 class="modal-title">{{task.title}}</h5>
        </div>

        <div class="modal-body" style="height: 200px; overflow-y: auto;">
            <h3>Are you sure you want to delete this task?</h3>
            <form method="post" >
                {% csrf_token %}
                <button type="submit" class="button delete-button">Yes, delete</button>
            </form>
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>

    </div>
</div>



 {% endcomment %}

templates/tasks/task_detail.html
{% comment %} 


<div id="task-details" style="width: 500px; height: 300px; ; border: 2px solid #000; border-radius: 10px; margin: auto; position: relative; transition: opacity 0.5s;">
    <div style=" padding: 10px; text-align: center;">
        <h5> {{ task.title }} </h5>
        <p> {{ task.description }} </p>
        
    </div>
</div>
 {% endcomment %}



<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

        <div class="modal-header">
            <h5 class="modal-title">{{task.title}}</h5>
        </div>

        <div class="modal-body" style="height: 300px; overflow-y: auto;">
            <p>{{task.description}}</p>
            {% comment %} <button></button> {% endcomment %}
        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>

    </div>
</div>

templates/tasks/task_form.html
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

        <div class="modal-header">
            <h5 class="modal-title">Add Task</h5>
        </div>

        <div class="modal-body" style="height: 450px; overflow-y: auto;">
            <form method="post" action="add/">
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="id_title">Title:</label>
                    <input type="text" name="title" class="form-control" maxlength="255" required id="id_title">
                </div>
            

                <div class="form-group">
                    <label for="id_description">Description:</label>
                    <textarea name="description" class="form-control" rows="10" required id="id_description"></textarea>
                </div>
                
                <br>

                <input class="btn btn-success" type="submit" value="Create" >
            </form>
        </div>



    </div>
</div>

templates/tasks/task_list.html
{% extends "base.html" %}

{% block content %}




    <br>
    <h1 style="margin-left: 15px"> Tasks </h1>
    <br>

    <button class="btn btn-primary" 
        style="margin-left: 15px"
        hx-trigger="click" 
        hx-get="{% url 'task-create' %}"
        hx-target="#task-create"


        data-bs-toggle="modal" 
        data-bs-target="#task-create">
        Add new Task
    </button>

    <br>

    <div id="task-create"
        class="modal modal-blur fade"
        style="display: none"
        aria-hidden="false"
        tabindex="-1">
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content"></div>
        </div>
    </div>


    <div id="task-details"
        class="modal modal-blur fade"
        style="display: none"
        aria-hidden="false"
        tabindex="-1">
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
            <div class="modal-content"></div>
        </div>
    </div>


    <br>
    <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">
                {% for task in tasks %}
                <div class="col">
                    <div class="card" style="margin-bottom: 25px;">
                        <div class="card-body">
                            <h5 class="card-title">{{ task }}</h5>
                            <p class="card-text">{{ task.description }}</p>
                            <button class="btn btn-warning" 
                                    hx-trigger="click" 
                                    hx-get="{% url 'task-update' task.id %}"
                                    hx-target="#task-details"
                                    {% comment %} hx-swap="outerHTML" {% endcomment %}

                                    data-bs-toggle="modal" 
                                    data-bs-target="#task-details">
                                    Update
                            </button>
                        </div>
                    </div>
                </div>
                {% endfor %} 
        </div>
    </div>

    
    



{% endblock %}

templates/tasks/task_update.html
{% comment %} <div id="task-delete"
    class="modal modal-blur fade"
    style="display: none"
    aria-hidden="false"
    tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content"></div>
    </div>
</div> {% endcomment %}



<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">

        <div class="modal-header">
            <h5 class="modal-title">Edit Task: {{ task.title }}</h5>
            <form method="post" action="{% url 'task-delete' task.id %}">
                {% csrf_token %}
                <input class="btn btn-danger" type="submit" value="DELETE"></input>
            </form>
        </div>

        <div class="modal-body" style="height: 500px; overflow-y: auto; " >
            <form method="post" action="{% url 'task-update' task.id %}" >
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="id_title">Title:</label>
                    <input type="text" name="title" class="form-control" maxlength="255" required id="id_title" value="{{ task.title }}">
                </div>

                <div class="form-group">
                    <label for="id_description">Description:</label>
                    <textarea name="description" class="form-control" rows="10" required id="id_description">{{ task.description }}</textarea>
                </div>
                <br>
                <div class="form-group form-check">
                    <input type="checkbox" name="completed" class="form-check-input" id="id_completed" {% if task.completed %}checked{% endif %}>
                    <label class="form-check-label" for="id_completed">Completed</label>

                </div>

                <div class="form-group row">
                    <label for="review_time" class="col-sm-3 col-form-label">Review Time:</label>
                    <div class="col-sm-9">
                        <select name="review_time" id="review_time" class="form-control">
                            <option value="1">After 1 Day</option>
                            <option value="2">After 2 Days</option>
                            <option value="">No Review</option>
                            <!-- Add more options as needed -->
                        </select>
                    </div>
                </div>
                
            
                <input class="btn btn-warning" type="submit" value="Update">
            </form>

        </div>
    </div>
</div>